"""add entry_commissions strikeprice expiry_dt columns

Revision ID: 94312dbffa3d
Revises: 
Create Date: 2025-12-02 21:37:28.342433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94312dbffa3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('strikeprice', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('expiry_dt', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('entry_commissions', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('exit_commissions', sa.Float(), nullable=True))
    op.drop_column('trades', 'commissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('commissions', sa.FLOAT(), nullable=True))
    op.drop_column('trades', 'exit_commissions')
    op.drop_column('trades', 'entry_commissions')
    op.drop_column('trades', 'expiry_dt')
    op.drop_column('trades', 'strikeprice')
    # ### end Alembic commands ###
